services:
  - type: web
    name: fabula-social-space
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn FabulaSocialSpace.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.tfwxfldcwnkuhzenigoo:pawmamirpajay@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
      - key: DJANGO_SECRET_KEY
        value: &=*sj7h+s-cz2if_i&sx2o=6*-!4h@q)#zfizu8@rxk0g)6r+k
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: "*"